version: '2'

services:

  jenkins:
    image: jenkins:2.60.1
    volumes:
      - './jenkins_home:/var/jenkins_home'
    ports:
      - "8080"

  nginx:
    image: nginx
    ports:
      - "8088:80"
    links:
      - jenkins
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
    environment:
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 8088
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: youremail@example.com

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

